server:
  port: 8081
spring:
  application:
    name: microservice-consumer-movie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#slf4j的日志级别
logging:
  level:
    com.tension.cloud.study.feignclient.UserFeignClient: debug
feign:
  client:
    config:
      #单个服务的配置，替换为default为通用配置
      microservice-provider-user:
        loggerLevel: basic
