spring:
  application:
    name: microservice-discovery-eureka
  profiles:
    active: peer1
---
spring:
  profiles: peer1
server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    #向其它eureka服务进行注册
    register-with-eureka: true
    #获取其它eureka服务的信息
    fetch-registry: true
  instance:
    hostname: peer1
---
spring:
  profiles: peer2
server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: peer2

